
DATABASE_URI: 'postgres://cogblzrfnnooxh:aa4d6a3fc171ff3f37a45e4925e7339bfe2a47d245ef80ff2de99c8873fc2bfb@ec2-54-89-49-242.compute-1.amazonaws.com:5432/d8vfvivqh45cr6'
DISCORD_TOKEN: 'NzQyNTE5OTUxNjc1NDkwMzY1.XzHTlw.TyIinmGXHPP7pLhsv6HWe8aqkro'



